### PR TITLE
add webpage viewer

### PR DESCRIPTION
**Pull request by Sebastian-ubs**
This is the ground work for a generic, config driven online resource viewer extensions.

This includes
- Showing how to add commands that spawn web pages inside of Platform
- 7 example web pages
- reloading pages on scripture reference and scroll group changes, so that web pages stay up to date with the current scripture reference
- retaining the web page on layout changes and restart of platform

👉 [Demo](https://drive.google.com/file/d/1qvToylTsfNxcSU8cQPzJclwupIx4JbRN/view?usp=sharing)

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/platform-bible-sample-extensions/13)

### CODE REVIEW

**Comment by Sebastian-ubs** [comment]
Structure was copied from verseRef extension. Interesting files to review are
- main.ts
- webViewerOptions.ts

Maybe
- types/online-resource-viewer.d.ts
- contributions/menus.json
- contributions/localizedStrings.json

**Review by tjcouch-sil — COMMENTED** [review]
The demo looks great! I haven't reviewed the code deeply yet, but I have a quick question as I don't see any commit messages indicating such: did you add this extension with `npm run create-extension -- web-viewer`? If not, would you mind doing this please? You will need to move your current folder somewhere else temporarily. If this script is not run to add the extension, getting updates from the template via scripts will not work, and it will lead to someone else (the two other times this has happened, I have been the one to fix it... :p ) having to do a bunch of extra work to get it to be based on the template and update via scripts. Then that person has to manually re-add the changes from the extension, which could lead to missing something and causing bugs. Then all the code will look like that person wrote it, too, which makes history confusing and difficult to trace.

> *[Reviewable](https://reviewable.io/reviews/paranext/platform-bible-sample-extensions/13#-:-OCEJsnj-H56CWZW1BIX:b8vg34a)* status: 0 of 40 files reviewed, all discussions resolved

**Comment by Sebastian-ubs** [comment]
I've not used `npm run create-extension -- web-viewer` but will do that now.
Also I think this code might be a little too verbose due to the reason mention in 3. in [Discord: improvement requests for papi](https://discord.com/channels/1064938364597436416/1309178528784187433/1309178548832960643)

**Comment by Sebastian-ubs** [comment]
because of the above will have to open a new PR

**Pull request closed without merging**
